# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('image_path', models.ImageField(upload_to='photos/')),
                ('timestamp_posted', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('alternative_text', models.CharField(blank=True, max_length=120, null=True)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('artist', models.CharField(blank=True, default='Saba', max_length=120, null=True)),
            ],
        ),
    ]
