# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_photos', '0002_auto_20160727_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width',
        ),
        migrations.AddField(
            model_name='photo',
            name='height_field',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width_field',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.ImageField(height_field='height_field', upload_to='photos/', width_field='width_field'),
        ),
    ]
